### PR TITLE
feat: make expanded topic stick

### PR DESCRIPTION
**Pull request by jahtomini**
Fixes: #36 

When a topic is selected and its contents expanded, it will now be sticky, while allowing the user to scroll through its contents independently of the viewport.

### CODE REVIEW

**Comment by ankiiitraj** [comment]
can you please add a screenshot or gif as well for demo 
thanks

**Comment by jahtomini** [comment]
Sure, here you go
doto_client_sticky_topic_demo

**Comment by jahtomini** [comment]
Oops I was just pushed another commit making some fixes

**Comment by ankiiitraj** [comment]
aah sure

**Pull request merged**
