### PR TITLE
Modified the Navbar

### PR DESCRIPTION
**Pull request by blackviking27**
Modified the Navbar to be responsive.

### CODE REVIEW

**Comment by ankiiitraj** [comment]
@vishal19111999 have a look at this https://deploy-preview-9--dotodsa.netlify.app/about

**Comment by Vishal19111999** [comment]
@blackviking27 conventionally hamburgers are on the left, so it is recommended to make either of these 2 modifications:

1. putting the hamburger on the left and the logo in the center
2. hiding the profile picture in mobile view

@ankiiitraj @blackviking27 views are welcome!

**Comment by blackviking27** [comment]
I added the neccessary changes @Vishal19111999 , check them out and let me know

**Comment by ankiiitraj** [comment]
https://602032bc53c6bb0007dcbec5--dotodsa.netlify.app/about new preview link

**Comment by ankiiitraj** [comment]
Contrast is missing, the text is less readable. check the ss.
Screenshot from 2021-02-08 00-22-50

else LGTM!

**Comment by blackviking27** [comment]
Changed the color, @ankiiitraj

**Review by ankiiitraj — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
